import { FileSearch, Users, Scale } from "lucide-react";
import RiskClassificationSection from "@/components/governance/RiskClassificationSection";

const Governance = () => {
  return (
    <section className="container mx-auto max-w-5xl px-4 py-12 animate-page-in">
      {/* Page header */}
      <div className="mb-10 animate-card-in">
        <h1 className="font-display text-3xl font-bold text-foreground">AI Governance & Safeguards</h1>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          DepEd follows a risk-based approach to AI governance, ensuring that every AI tool used in basic education meets standards for safety, privacy, and ethical use.
        </p>
      </div>

      {/* ── Risk Classification Interactive Section ── */}
      <RiskClassificationSection />

      {/* PIA */}
      <div className="mb-10 animate-card-in" style={{ animationDelay: "320ms" }}>
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
          <div className="flex items-start gap-3">
            <FileSearch className="mt-0.5 h-6 w-6 shrink-0 text-primary" />
            <div>
              <h2 className="font-display text-lg font-bold text-foreground">Privacy Impact Assessment (PIA)</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                A Privacy Impact Assessment evaluates how an AI system collects, stores, processes, and shares personal data — especially the sensitive data of learners and teachers. It identifies privacy risks and recommends measures to mitigate them. In DepEd, a PIA ensures compliance with the <strong className="text-foreground">Data Privacy Act of 2012</strong> and guidelines from the National Privacy Commission (NPC). Every AI tool that handles personal information must have a completed or in-progress PIA before deployment.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Compliance */}
      <div className="mb-10 animate-card-in" style={{ animationDelay: "400ms" }}>
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
          <div className="flex items-start gap-3">
            <Scale className="mt-0.5 h-6 w-6 shrink-0 text-primary" />
            <div>
              <h2 className="font-display text-lg font-bold text-foreground">Conformity / Compliance Assessment</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                This assessment evaluates whether an AI system complies with applicable laws, regulations, standards, and DepEd policies. It includes alignment with national and international AI governance frameworks such as the <strong className="text-foreground">Data Privacy Act</strong>, <strong className="text-foreground">ISO/IEC AI standards</strong>, <strong className="text-foreground">UNESCO AI in Education guidance</strong>, and <strong className="text-foreground">ASEAN AI principles</strong>. The registry records whether each tool has undergone this assessment, is in progress, or has not yet been initiated.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Human-in-the-Loop */}
      <div className="mb-10 animate-card-in" style={{ animationDelay: "480ms" }}>
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
          <div className="flex items-start gap-3">
            <Users className="mt-0.5 h-6 w-6 shrink-0 text-primary" />
            <div>
              <h2 className="font-display text-lg font-bold text-foreground">Oversight & Human-in-the-Loop</h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                Human-in-the-loop means that all outputs and decisions generated by an AI system are subject to human review, validation, or intervention. In DepEd, <strong className="text-foreground">teachers, school heads, and designated officials remain the final decision-makers</strong> — especially in matters affecting learners' rights, educational outcomes, or personal data. AI supports professional judgment; it never replaces it. This safeguard protects against over-reliance on AI and ensures accountability at every level.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Governance;
